# Generated by Django 4.1.5 on 2023-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTrade', '0006_alter_contact_id_alter_stock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='null', max_length=20)),
                ('balance', models.FloatField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='null', max_length=20)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='null', max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('buyPrice', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('buyDate', models.DateField(auto_now_add=True)),
                ('month', models.CharField(default='2022-01', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='null', max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('buyPrice', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('sellPrice', models.FloatField()),
                ('sellDate', models.DateField(auto_now_add=True)),
                ('month', models.CharField(default='2022-02', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='null', max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('buyPrice', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('buyDate', models.DateField(auto_now_add=True)),
                ('month', models.CharField(default='2022-02', max_length=20)),
            ],
        ),
    ]
